# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------
menu:
  home: /
  archives: /archives
  categories: /categories
  tags: /tags
  about: /about

# ---------------------------------------------------------------
# Favicon Settings
# ---------------------------------------------------------------

favicon: /assets/loong.jpeg